.\" This file is part of si53xx, see <https://qu1x.org/si53xx>.
.\" 
.\" Copyright (c) 2016 Rouven Spreckels <n3vu0r@qu1x.org>
.\" 
.\" si53xx is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU Affero General Public License version 3
.\" as published by the Free Software Foundation on 19 November 2007.
.\" 
.\" si53xx is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
.\" GNU Affero General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Affero General Public License
.\" along with si53xx. If not, see <https://www.gnu.org/licenses>.
.\"
.TH si53xx\-map 1 "May 9, 2016" "si53xx\-1.0.0" "si53xx"
.SH NAME
si53xx\-map \- si53xx map converter
.SH SYNOPSIS
.B si53xx\-map
[\fIHDR\fR]...
.SH DESCRIPTION
Convert and rename \fIHDR\fR .h files to .map files.
.PP
With no files, print help.
.SH EXIT STATUS
.TP
.B 0
Success
.PP
Errors within the user\-defined range from \fB64\fR to \fB113\fR:
.TP
.B 64
Cannot read .h file.
.TP
.B 65
Cannot write .map file.
.TP
.B 66
Cannot remove .h file.
.SH EXAMPLE
.TP
.B si53xx\-map *
Convert all .h files of current directory to .map files.
.SH COPYRIGHT
Copyright \[co] 2016 Rouven Spreckels <n3vu0r@qu1x.org>
.PP
si53xx is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License version 3
as published by the Free Software Foundation on 19 November 2007.
.PP
si53xx is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.
.PP
You should have received a copy of the GNU Affero General Public License
along with si53xx. If not, see <https://www.gnu.org/licenses>.
.SH WEBSITE
<https://qu1x.org/si53xx>
.SH AUTHORS
Rouven Spreckels <n3vu0r@qu1x.org>
.SH SEE ALSO
.B si53xx(1) si53xx\-cmp(1)
